---
title: "Advisee Guide"
bibliography: references.bib
output: 
  html_document:
    toc: true
    number_sections: true
    toc_float: true
params:
    n: 100
    d: !r Sys.Date()
---

----

<center>"Remember that your major professor is a busy person. If he [or she] isn't, get a different major professor." *Anonymous*</center>

----

<center> "The more you know, the more you know what you don't know" -Richard Feynman</center>

----

# Expectations {#id}
Below you will find details regarding my expectations as a major professor. Our mutual agreement to work together as advisor/advisee entails that you accept the conditions outlined throughout this document. Please remember that these expectations go both ways and that you should feel free to ask me about my approach to advisees.

Choosing a major professor is an important first step in completing your graduate education. Keep in mind that if you have not had a class with a particular faculty member, it is not likely that this professor will be a suitable advisor. In fact, if you have not had a class with me, **do not** ask me to be your major professor; I will say no. In [Section 4](#you-and-your-major-professor), I have provided some questions that you might ask as you consider who your major professor might be. This decision will be different for MA and PhD students, though some of the same criteria may apply.

## Collaborative Research
For anyone considering asking me to be his/her major professor, you will be expected to participate in some type of collaborative research with me. Collaborative research could include, for example, a conference presentation, a publication, or a joint grant application. MA students who choose to complete a thesis will be strongly encouraged to choose a research topic that complements my own research agenda. In linguistics, working with collaborative projects has become increasingly common, and I encourage this type of work with all my students. You should take advantage of your time as a graduate student to learn how to work on group research.

## Presenting papers/posters
In addition to working with me collaboratively, I expect you to present your research (either individually, with me, or in collaboration with other scholars) in academic settings. The first place to do so is at the **Romance Linguistics Colloquium** (held year-round) and the **Linguistics Colloquium** (held on Fridays in the Spring semester), each featuring talks by students and sometimes faculty from UGA and other institutions. Any student, MA or PhD, working with me is expected to give at least one presentation in the RLC related to his/her thesis/dissertation research; **this is not optional**. Moreover, there are a number of conferences that would be good venues for your work, e.g., the *Hispanic Linguistics Colloquium*, *Workshop on Spanish Sociolinguistics*, *Linguistic Symposium on Romance Languages*, *Southeastern Conference on Languages and Literatures*, *New Ways of Analyzing Variation*, *Annual LSA Meeting*, among many others. Presenting at academic conferences is one of the best ways to meet other students and faculty interested in your topic and to get feedback on your research. UGA has a number of resources available to students attending conferences, including departmental funds and Graduate School support.

## Teaching
If you are a graduate assistant at UGA, you will have a number of duties related to the teaching of your classes. Although I won't have a supervisory role in your teaching, I'm happy to offer advice as needed, such as it is. During each semester, my intention is to observe your teachoing at least once, just to have an idea of your teaching style so that I can address this in my letters of recommendation. Also, if you'd like for me to attend a class or would like to sit in on one of mind, just let me know. I've learned a lot about teaching from watching my students and am always looking to learn new approaches.

You should also be prepared to treat your teaching (like your research) as another opportunity for professional development. As such, I highly recommend consulting with the [UGA Center for Teaching and Learning](https://ctl.uga.edu/) which offers, among many other programs, a wide range of [opportunities for Graduate Students](https://ctl.uga.edu/grad-student/). Again, my primary focus regarding your education at UGA is helping you develop and execute a successful research program. But you should always look out for ways of improving your teaching.

## Submitting and Revising
At some point in your program (preferably sooner rather than later), I will give you a schedule specific to your program. This schedule will include dates for turning in different pieces of your MA thesis or dissertation. Regarding submission of materials, please keep in mind the following. Before any materials (in particular, chapters of a thesis or a dissertation) are submitted to the other members of your advisory committee, they will need to be approved by me. I will need to provide feedback on your work before you send it out to others. When you do submit something to me (and to others), it should be as polished as possible. **Do not** submit a set of bulleted notes and expect to get feedback. Finally, regarding turn-around times (see also the section on **Selecting a Chair and Committee**, my goal is to give you feedback on your work **no later than two weeks after submission**. I will make every effort to get your work returned to you in a timely manner.

Also, you should feel free (and in fact obliged) to send me other submissions that you might be working on. In particular, I will be happy to read drafts of conference abstracts and journal/proceedings submissions. At the very least, you should have one other set of eyes reviewing your work before you send it out. I (and your committee members) will certainly be available to give you feedback on these items.

## Letters of Recommendation
I am more than happy to provide letters of recommendation for my advisees, including those for whom I am not the major professor. However, please keep in mind that preparing multiple letters requires a considerable amount of time, even if the content of these letters is largely repeated for different applications. Thus, for any given letter writing venture that requires more than **five (5)** individual letters (e.g., letters for academic positions), students will be expected to use a dossier service, like [Interfolio]( http://career.uga.edu/graduate_school/interfolio). This requirement applies to anyone (advisees and non-advisees) who may request that I provide a letter of recommendation.

All requests for letters should be done with **at least three weeks of advance notice**. More substantive letters (e.g., letters for job applications), require more time; please keep this in mind as you plan your requests. When you ask for a letter (or letters), I'll need the following:

1. Complete information about the program or job that you are applying for: This includes description of the job or the name of the specific degree program / study abroad program and a link to the program website, the name and address of the person to whom the letter should be sent [if it is not a standard online recommendation form, other special instructions concerning the letter, and the <font size="3" color="red">deadline</font>.
2. Copies of other documents that you may be submitting along with your application (e.g., a CV or resumé, writing sample): These can be rough drafts. If you are applying for an academic position you must include a draft of your cover letter.
3. Names and dates for the courses you took with me along with some indication of the work that you did in theses courses (e.g., titles of final papers): This will help in making sure that my memory doesn't get in the way of providing helpful (and accurate) details in the letter.
4. Any additional information that might be useful: It's often the case that I make mention in my letters of extracurricular accomplishments. If you feel that there's something you'd like for me to address, then you should certainly provide me with additional materials.

Finally, I need to make two additional points regarding letters. First, unless you're certain that I can provide a generally positive letter, then you should reconsider asking me for one. The better I know you and your work, the more specific the letter will be. But if you don't believe that I will serve as a good or accurate recommender, then please ask someone else. Second, I welcome and appreciate ``Gentle Reminders'' as needed, particularly as a deadline approaches.

## Tech Savvy
In completing your thesis or dissertation, you should make every effort to learn new skills that will be useful to in field. This includes research skills (e.g., quantitative analysis), software, and equipment. Starting in **Fall 2020**, all advisees will be required to use the newly revised [UGA Dissertation LaTeX Template](https://github.com/DigiUGA/UGA-Dissertation-LaTeX-Template), developed by Joey Stanley and Jonathan Crum. There are lots of resources for learning how to use LaTeX, including some available through the [UGA DigiLab](https://digi.uga.edu/digilab/#1544564021635-6ae22572-cb2d). For the purposes of working with me as an advisee, knowledge of the following resources will be required:

1. **LaTeX**: As you will find out, there are plenty of ways to **LaTeX** (yes, it's a verb!). One particularly easy way is to use [Overleaf](https://www.overleaf.com/) which has a number of useful features that make getting started with **LaTeX** relatively easy. You can also **LaTeX** on your local machine (i.e. your laptop) using editors like [Atom](https://atom.io/) or [TexMaker](https://www.xm1math.net/texmaker/).
2. [Zotero](https://www.zotero.org/) (or some similar citation management system): Keeping track of what will end up being many references requires some tool designed for this purpose, especially since you will be using **LaTeX**. I recommend Zotero but there are others (e.g., Endnote).
3. [R](https://www.r-project.org/) and [RStudio](https://rstudio.com/): At this point, using R and RStudio are standard in the field. There are **numerous** books about using R in linguistics (e.g., @gries_statistics_2013, @desagulier_corpus_2017, and @winter_statistics_2020), in addition to other resources available for learning more about R.-->
4. [ELAN](https://archive.mpi.nl/tla/elan): This is an annotation tool for audio and video recordings created by the great folks at the [Language Archive](https://archive.mpi.nl/tla/).

This (woefully inadequate) list should provide you with a sense of my expectations regarding the skills you should be learning. There will be many other resources that will be useful as you navigate your research and teaching interests. If you have no background in coding or using programs like these, welcome to the club.  Remember that now is the time for you to expose yourself to as many new ideas and techniques as possible. Take this time to push yourself into new areas, even it requires moving out of your tech-comfort zone. I strongly encourage you to interact with me and your fellow students in learning more about these resources. If you would like for me (or someone else) to arrange a workshop that covers any of these resources, I am more than happy to do that.

## Get a Graduate Certificate

While at UGA, you should consider expanding your training by enrolling in one of the many interesting and useful graduate certificate programs offered. If you're considering a career in academia, a certificate can help to distinguish you from other candidates and can also demonstrate your skills beyond your core areas of interest. A certificate is also quite handy for careers oustide of academia (see the following section on Alt-Ac careers). Here are a few possibilities for certificates you might pursue at UGA:

1. [Latin American and Caribbean Studies](https://grad.uga.edu/index.php/degree/latin-american-and-caribbean-studies/)
2.  [African American Studies](https://grad.uga.edu/index.php/degree/african-american-studies/)
3.  [Diversity, Equity, and Inclusion](https://grad.uga.edu/index.php/degree/diversity-equity-and-inclusion/)
4.  [Geographic Information Science](https://grad.uga.edu/index.php/degree/geographic-information-science/)
5.  [Qualitative Studies](https://grad.uga.edu/index.php/degree/qualitative-studies/)
6.  [University Teaching](https://grad.uga.edu/index.php/degree/university-teaching/)
7.  [Women's Studies](https://grad.uga.edu/index.php/degree/university-teaching/)
8.  [Graduate Certificate eLearning Design](https://online.uga.edu/degrees-certificates/graduate-certificate-elearning-design)

These are just a few of the certificate options. I encourage you to explore these opportunities.

## Alt-Ac (Alternate Academic) Careers

I don't know how long this term has been around (i.e. Alt-Ac or Altac), but it is now the reality that most graduate students live in. Given that (a) the job market is much tighter than it used to be and (b) grad students are much better prepared (and smarter) than I was/am, having some 'outside-the-university-box' options (forgive the trite expression) is a good idea. There are some resources available, like this library source from [UNC Chapel Hill](https://guides.lib.unc.edu/altac). For my part, I am dangerously uninformed about this topic, but I will be adding some resources here in the **very near** future to help.

----

# Academic Requirements

## MA Students

For information regarding the MA in Hispanic Linguistics, please read carefully both the [Degree Requirements](http://www.rom.uga.edu/ma-hispanic-linguistics) and the [Romance Languages Graduate Handbook](http://www.rom.uga.edu/graduate-handbook), in particular [section III.2](http://www.rom.uga.edu/graduate-handbook#III2). This section provides a ``Suggested Timetable to Complete the M.A. program'', which is normally done in two years. For students in the Department of Linguistics, you should read the information regarding the [MA (thesis)](https://ling.franklin.uga.edu/graduate/ma-thesis-introduction) or [MA (non-thesis)](https://ling.franklin.uga.edu/graduate/ma-non-thesis-introduction). The [Checklist in Section III.2.g](http://www.rom.uga.edu/graduate-handbook#III2) explains the specific requirements for completion of the MA, most of which apply both to students in Romance Languages and  Linguistics. Students from the Department of Linguistics should also consult the website regarding [Graduate Advising](http://linguistics.uga.edu/graduate-advising) as well as the [Linguistics Graduate Student Handbook](https://ling.franklin.uga.edu/sites/default/files/inline-files/Graduate%20Handbook%20Revised%20Feb%202020.pdf). In addition to this information, you should also consider the following:

- **All** linguistics students (regardless of their particular areas of interest) should complete the [Internal Review Board (IRB) training](https://research.uga.edu/hrpp/irb/) required for working with human subjects. Ideally, you should do this during your **first semester**.
- If you're planning to do fieldwork or experiments, I strongly urge you to apply for funding (see Section on **Funding Opportunities**). Even if you don't receive any funds, the experience of applying will be beneficial.
- Even though studying or working in the summer is not strictly speaking required, it is an ideal time to complete data collection or experiment development/implementation. In fact, taking courses over the summer can be a good way to get a jump on your coursework. In addition to occasional offerings from Romance Languages, the Statistics Department routinely offers **STAT 6210/6220 and 6315**, both of which offer students comprehensive coverage of the types of quantitative methods used in linguistic research. For a more specific introduction, however, I strongly recommend that students take \textbf{LING 4400/6400}, "Quantitative Methods in Linguistics."
- Students working with me, as either MA or PhD students, will be *required* to present their research at some forum held on campus, such as the Romance Languages Colloquium or the Linguistics Colloquium. MA students will be expected to present in the fall or spring of their second year.

Below is a (non-exhaustive) list of theses that I have directed:^[For an exhaustive list of the theses I've directed, along with abstracts, see the [Student Section of my personal website for more examples](https://chadhoweuga.github.io/chowe/students/}{Student Section of my personal website for more examples)].

- **Ryan Dekker** (MA, Linguistics), Thesis Title: *Income Effects on a Speech Community: Oconee County within Northeastern Georgia* (2018)
- **Bethany Bateman** (MA, Romance Languages), Thesis Title: *Reportative evidentiality in Wounaan meu-Spanish bilinguals: A comparative examination of* dice(n) que (2015)
- **Philip Limerick** (MA, Romance Languages), Thesis Title: *Spanish subject expression in Roswell, Georgia: Dialect formation in an emerging bilingual community* (2014)
- **Kristen Fredriksen** (MA, Linguistics), Thesis Title: *Constraints on perfect auxiliary contraction: Evidence from spoken American English* (2012)
- **Kerry Steinberg** (MA, Romance Languages), Thesis Title: *Language Use, Language Attitudes and Mobility: The Case of the Rural and Urban Areas of Coronel Oviedo, Paraguay* (2010)
- **William Pennington** (MA, Romance Languages), Thesis Title: *Split antecedents and pronominal expressions in Spanish* (2008)
- **Ninosca Pérez Minchola** (MA, Romance Languages, Thesis Title: *El rol de la cortes\'ia en entrevistas políticas conflictivas en la televisión peruana* (2007)


> **_A note on Thesis vs. Non-Thesis_** The choice between doing the thesis or the non-thesis option of the MA is one that should be guided largely by your experiences in your first semester (or two) at UGA. After arriving at UGA, you should talk to your professors and get an idea of what you might be able to do for thesis research. Keep in mind that you're not necessarily expected to come up with a thesis topic completely on your own. Ideally, your research would relate to/interface with/contribute to the work being conducted by the faculty in the department. If you're considering moving onto a PhD after the MA, you should consider your decision of doing a thesis very carefully. Although the trend as of late seems to be that MA programs in Spanish Linguistics (and some in General Linguistics) do not require a thesis, completing a thesis-like project can be a good way of gauging your interest and ability in the field. Moreover, since the idea of a thesis is to have you produce a piece of research that is of sufficient quality to present at academic conferences and to publish in scholarly journals, then this work could be used as part of your application to PhD programs (should you be interested in pursuing a career in academics). In short, I urge you to keep your options open; you never know when you might be struck by inspiration and decide that research on the complex nature of variable past reference in Spanish is indeed your true calling.

## PhD Students

So, you've decided to do a PhD. You will likely find yourself in the position of asking yourself (and having others ask you) "Why are you doing this?". This is normal and will continue throughout your career in academia. The more relevant question to ask yourself at this point is "How am I going to get this done?". For students in Romance Languages, you should consult the [Degree Requirements for the PhD in Hispanic Linguistics](http://www.rom.uga.edu/ph-d-hispanic-linguistics) as well as the [relevant sections of the RL Graduate Student Handbook](http://www.rom.uga.edu/graduate-handbook#III3). Once again, you should pay close attention to the sections outlining the Suggested Timetable (III.3.g) and the Checklist (III.3.h). For students in the Department of Linguistics, you should consult the following information provided in [this section of the departmental website](https://ling.franklin.uga.edu/graduate/phd-introduction}{this section of the departmental website).

Like any life choice, choosing to do a PhD should be approached with considerable care and preparation. There are **many** resources on the internet regarding this question, and I would suggest going through them before you commit. It's also a good idea to take a look at resources like the *Chronicle of Higher Education*, which has resources regarding the academic job market. I also recommend a document entitled [How to Be a Successful PhD Student](http://people.cs.umass.edu/~wallach/how_to_be_a_successful_phd_student.pdf) (by Mark Dredze at Johns Hopkins University and Hanna M. Wallach University of Massachusetts Amherst). In addition to many other helpful comments, Dredze and Wallach note that "[g]etting a PhD takes a long time and a great deal of dedication and hard work. Unless you really want it, you will not finish the PhD." A healthy dose of practical consideration is helpful before embarking on a program of doctoral study.

Here are a few things you have to keep in mind if you're considering doing a PhD in general and with me more specifically:

- As mentioned in the section on **Expectations**, you should make every effort during your doctoral studies to expose yourself to new ideas. This includes (but is not limited to) attending lectures, learning new research techniques/methods, engaging in collaborative research with faculty and other students, and taking courses (when possible) that are not necessarily required by your program of study.
- Students working with me, as either MA or PhD students, will be **required** to present their research at the Romance Languages Colloquium and the Linguistics Colloquium. MA students will be expected to present in the fall or spring of their second year. PhD students will present at least once in the RLC.
- Applying for funds to conduct research is part and parcel of what you'll be doing in academics. And though getting a research grant is time-consuming and often frustrating, it is absolutely essential to your formation as a scholar to solicit funding for your work. In the section on **Funding**, I explain some of the resources available for research funding. Please have a look at these resources. If you know of any that aren't included, feel free to let me know.
- As a PhD student, you will be focusing more and more on an exceptionally small piece of the larger realm of scholarly exploration. However, this is not an excuse to avoid taking courses in other linguistic disciplines (or even from other areas of the humanities or social sciences). Indeed, some of the best research is conducted at the interfaces between areas of study (e.g., linguistics and sociology) and should be considered as viable areas of inquiry. However ...
- If you find yourself interested in some topic that you know to be well outside my wheelhouse (which includes a lot of issues), it's probably better that you ask someone else to be your Major Professor. More generally, you should know what the interests of your potential advisor and committee members are so that you can begin to plan your thesis project accordingly.
- Invest some effort in reading about how to accomplish your degree objectives. Some oldies but goodies include @bolker_writing_1998 and @macaulay_surviving_2011, but there are many others.



----


# Program Requirements {.tabset}

If you're planning on asking me to be your Major Professor, you will be required to meet the following deadlines. **Failure to meet these deadlines may result in the postponement of the completion of your degree or termination of your program**.

## MA Students

1. *Choose a major professor*: If you're planning to ask me to direct your thesis, you need to make this request no later than <font size="3" color="red">the end of your 2nd semester</font>the end of your 2nd semester} (Important dates are indicated in red.). You should first take some time to come and talk to me to discuss the type of project you're interested in doing.
2. *Selecting a thesis topic*: This, of course, can be done in conjunction with the selection of your Major Professor. If you are working with me, you will need to submit, in writing, a proposed thesis topic (2 pages) no later than <font size="3" color="red">the end of your 2nd (MA) semester</font>.
3. *Apply for funding, IRB, etc. for MA Thesis-related projects*: If your project requires data collection with human subjects (e.g., interviews, experiments, etc.), you will need to submit the required paperwork to the [IRB](https://research.uga.edu/hrpp/irb/). Also, if you need to travel, you should apply for funding during your <font size="3" color="red">2nd semester</font>.
4. *Selection of Advisory Committee*: There's a good chance that you will have already chosen the other members of your Advisory Committee. If not, we'll need to finalize your selection by the end of your <font size="3" color="red">2nd semester</font>.
5. *Complete fieldwork*: If you plan on working with me, chances are that you'll be asked to gather data of your own. So, you should plan on completing this part of your thesis research during the summer between your <font size="3" color="red">1st Spring semester and your 2nd Fall Semester</font>.
6. *Pass M.A. Examinations*

> **_MA in ROML_** "The M.A. written examinations will be given three times a year: in the <font size="3" color="red">2nd week of November</font>; in the <font size="3" color="red">5th week of the Spring Semester</font>; and in <font size="3" color="red">the 12th week of the Spring Semester</font>. Students choosing to write a thesis must take the M.A. written examinations in November. The examination in the 5th week of the Spring Semester will be reserved for students choosing the non-thesis option and students who failed the exam in November. The examination in the 12th week of Spring Semester will be reserved for students who failed the examination in the 5th week of Spring Semester. The Graduate Coordinator will inform students in writing of the date of the exams and ask them in turn to inform him or her of their intention to take the exam. Previous exam questions will be kept on file and made available to students."

> **_MA in LING_** For Masters students in the Department of Linguistics, there are also two options: [M.A. (Thesis)](https://www.linguistics.uga.edu/ma-thesis-introduction) and [M.A. (Non-Thesis)](https://www.linguistics.uga.edu/ma-non-thesis-introduction). The Thesis option does not require an exam, but the Non-Thesis option does. For more information regarding the Final Examination for M.A. (non-thesis) Students, please consult [the departmental website](https://www.linguistics.uga.edu/ma-non-thesis-final-exam).

7. *File appropriate paperwork*: There are a number of steps that are involved in moving towards completing your requirements for the M.A., some of which will be accomplished in the Spring Semester of your 2nd year (e.g., Application for Graduation). One of the forms that should be completed by the end of your 3rd semester is the Program of Study Form. See the [Graduate School Website](https://grad.uga.edu/index.php/current-students/forms/) for more details.
8. *Secure approval of thesis prospectus*: For MA students in ROML, you must prepare a prospectus outlining your thesis research and describing the main points that will be discussed (see section III.2.d. of the Handbook). This prospectus will be read by your Advisory Committee and discussed following your MA examinations. You must submit a complete draft of your prospectus <font size="3" color="red">the end of your third semester</font> (i.e. in December). Although there is no formal requirement of a prospectus for MA students in the Department of Linguistics, you will be required to prepare a proposal if you are working with me. A draft of this proposal must be submitted by <font size="3" color="red">the end of your third semester</font>.
9. *Submit 1st Draft of your thesis*: You will need to turn in a complete draft of your thesis (i.e. one that includes the body of the document, the bibliography, tables, etc., not just a collection of notes) by the beginning of your last semester in the program. The expectation is that uyou will be submitting chapters of your thesis before this time. These chapters will be reviewed by me and your other committee members (see section III.2.d. of the Graduate Student handbook). The complete draft should be submitted by the <font size="3" color="red">last Friday of January of your final semester</font>.
10. *Submit 1st Draft of your thesis*: You will need to turn in a complete draft of your thesis (i.e. one that includes the body of the document, the bibliography, tables, etc., not just a collection of notes) by the beginning of your last semester in the program. The expectation is that uyou will be submitting chapters of your thesis before this time. These chapters will be reviewed by me and your other committee members (see section III.2.d. of the Graduate Student handbook). The complete draft should be submitted by the <font size="3" color="red">last Friday of January of your final semester</font>.
11. *Submit revised draft of thesis*: The revising process takes time and will undoubtedly require several passes. You will be expected to have finished a complete revised draft no later than <font size="3" color="red">the end of February</font>.
12. *Schedule a defense*: All the final paperwork required for your graduation is due by the last week in April (see [Graduate School Deadlines](https://grad.uga.edu/index.php/current-students/important-dates-deadlines/). In order to provide proper time for any necessary revisions between your defense date and the date for completing all degree-related requirements, we will plan to have your defense in <font size="3" color="red">early to mid April</font>. This should provide you with ample time to apply any of the changes resulting from the defense and review by your Advisory Committee.
13. *Submit Thesis Draft for Review by Advisory Committee*: You will need to submit the 'final' version of your thesis to your committee <font size="3" color="red">no later than two weeks before the defense date</font>. This is done to provide your advisory committee enough time to provide comments and feedback on the final product. Also, it is at this point that your committee will sign (or not) the ["Approval for Master's Thesis and Final Oral Examination"](http://www.grad.uga.edu/forms&publications/student/body_apprform.pdf) for your thesis.
14. *Format Check for Graduate School*: See the [Graduate School website](http://www.grad.uga.edu/academics/deadlines.html) for more details.
15. *Thesis Defense*: Assuming your Advisory Committee has agreed that your thesis draft is ready to defense (using the ["Approval for Master's Thesis and Final Oral Examination"](http://www.grad.uga.edu/forms&publications/student/body_apprform.pdf), we will have the defense. The defense is expected to last no longer than 90 minutes and should include a brief (15 minute) presentation by you covering the main points of the thesis (e.g., research questions, hypotheses, background lit., methodology, results, discussion, and conclusions). During the defense, you will be asked questions about your thesis research. You talk to me in advance about the types of questions that you might receive and try to anticipate how you might address potential shortcomings. Remember, the defense is a **separate** piece of the MA process; having your committee agree that your thesis is defendable doesn't guarantee a favorable evaluation for the defense. Also, the defense is a public event, and, as such, you are welcome and encouraged to invite spectactors.
16. *Submit Final Paperwork*: Once you've submitted all the necessary revisions, I can sign off on the final version and submit the required (digital) paperwork to the Graduate School.
17. *Commencement*: If you're not planning to attend your commencement, you may need to let the Graduate School know before hand. You should at least consider attending, especially given what I will have just put you through. Besides, you get to wear fancy robes. Either way, please let me know what you plan to do vis-\`a-vis Commencement; I would very much like to attend if you are.
18. **Celebrate!**


> **_A note on summer defenses:_**  First and foremost, **under not circumstances will my advisees be permitted to defend their theses during the summer**. You will have to complete all of the requirements for Graduation in order to graduate in the spring. Failure to do so will result in postponement or early termination of your degree. Again, I will NOT be available for thesis defenses during the summer semester so do not consider this an option. If under some exceptional circumstance you cannot fulfill your degree requirements during the spring semester, it may be possible to defend during the following fall semester. Doing so, however, may require you to pay for your own tuition. You will need to consult the Graduate School and the Romance Graduate Student Handbook for more detailed information. Nevertheless, such arrangements will only be made under **extraordinary** circumstances and are subject to the availability of your Advisory Committee members.


----

## PhD Students

The process of completing a PhD is, to put it bluntly, difficult, as it should be. You will inevitably find yourself drawn to a variety of different areas of inquiry, each interesting and distracting in its own way. However, I urge you to formulate a concise calendar from the very beginning; this will give you a measure of how you're progressing in your program of study. Remember, at this stage in your career, it's not enough to check boxes, but it sure does help to have some boxes to check.

You should be aware that as of **Spring 2020** that doctoral students in both Romance Languages and Linguistics have the option of completing a set of two research papers, typically referred to as *qualifying papers (QP)*. The expectations for these papers are quite similar for students in both departments, but you should consult the [ROML Handbook](https://rom.uga.edu/graduate-handbook#III3) and the [Linguistics Research Paper](https://www.linguistics.uga.edu/comprehensive-exam-and-dissertation) format for further details. If you are working with me, you will be expected to have your **QP1** ready by your <font size="3" color="red">third semester</font> in the program. Your **QP2** should be completed by your <font size="3" color="red">fifth or sixth semester</font>. I have plenty of QP samples; feel free to request a copy. The following schedule provides an overview for students wanting to take the comprehensive exams.

1. *Preliminary Forms*: Complete the the [Preliminary Doctoral Program of Study form](https://grad.uga.edu/index.php/current-students/forms/) and present it to the Graduate Coordinator by <font size="3" color="red">the end of your 2nd semester</font>. You'll also need to complete the [Advisory Committee form](https://grad.uga.edu/index.php/current-students/forms/), which assumes that you'll need to have chosen a Major Professor (also by <font size="3" color="red">the end of your 2nd semester</font>). Note that some of these forms should be completed using the onine portal provided by the Graduate School. You should first take some time to come and talk to me to discuss the type of project you're interested in doing.
2. *Complete coursework*: By <font size="3" color="red">the end of your fourth or fifth semester</font>, you will complete your coursework and prepare for your comprehensive examinations (or qualifying papers in the case of students from the Linguistics Department).
3. *Final Program of Study Form*: You will need to complete the [Final Program of Study form](https://grad.uga.edu/index.php/current-students/forms/) by <font size="3" color="red">the end of the fourth or fifth semester</font> as well.
4. *Secure approval of thesis prospectus*: You will need to prepare a prospectus outlining your thesis research and describing the main points that will be discussed. This prospectus will be read by your Advisory Committee and discussed following your Comprehensive examinations. Ideally, your prospectus will be completed by <font size="3" color="red">the end of your third fifth semester</font>. For additional information regarding how to develop your prospectus, consult the [PhD. Prospectus Guidelines](http://linguistics.uga.edu/graduate/phd/phd-prospectus-guidelines).
5. Once you've secured approval for your thesis prospectus, you can proceed with your project. If this involves human subjects data gathering, then you will need to submit the required paperwork to the [IRB](https://research.uga.edu/hrpp/citi-training/). Also, if you need to travel, you should apply for funding during your <font size="3" color="red">third and fourth years</font>.
6. **NOTE!** Please keep in mind that once you've finished all the tasks related to your comprehensive exams and your prospectus, we will be set up a work schedule that is catered to your individual project. This will include deadlines for submitting dissertation materials (i.e. chapters) and dates for meetings. We may in fact start doing this **before** the comprehensive exam process.
7. File an Application for May Graduation, Program of Study, and Advisory Committee Form: See the [Graduate School Website](https://grad.uga.edu/index.php/current-students/important-dates-deadlines/) for more details.
8. *Schedule a defense*: All the final paperwork required for your graduation is due by the first week in May (see [Graduate School Deadlines](https://grad.uga.edu/index.php/current-students/important-dates-deadlines/)). In order to provide proper time for any necessary revisions between your defense date and the date for completing all degree-related requirements, we will plan to have your defense in <font size="3" color="red">early to mid April</font>. This should provide you with ample time to apply any of the changes resulting from the defense and review by your Advisory Committee.
9. *Submit Thesis Draft for Review by Advisory Committee*: You will need to submit the 'final' version of your thesis to your committee <font size="3" color="red">no later than three weeks before the defense date</font>. This is done to provide your advisory committee enough time to provide comments and feedback on the final product. Also, it is at this point that your committee will sign (or not) the ["Approval for Master's Thesis and Final Oral Examination"](https://grad.uga.edu/wp-content/uploads/2019/08/body_appphddis_v2-1.pdf) for your thesis.
10. *Format Check for Graduate School*: See the [Graduate School website](https://grad.uga.edu/index.php/current-students/important-dates-deadlines/) for more details.
11. **Dissertation Defense**: Assuming your Advisory Committee has agreed that your dissertation draft is ready to defense, we will have the defense. The defense is expected to last no longer than 120 minutes and should include a brief (15-20 minute) presentation by you covering the main points of the thesis (e.g., research questions, hypotheses, background lit., methodology, results, discussion, and conclusions). During the defense, you will be asked questions about your thesis research. You talk to me in advance about the types of questions that you might receive and try to anticipate how you might address potential shortcomings. Remember, the defense is a **separate** piece of the PhD process; having your committee agree that your thesis is defendable doesn't guarantee a favorable evaluation for the defense.
12. *Submit final paperwork*: Once you've submitted all the necessary revisions, I can sign off on the final version and submit the required paperwork to the Graduate School.
13. *Commencement*: If you're not planning to attend your commencement, you may need to let the Graduate School know before hand. You should at least consider attending, especially given what I will have just put you through. Besides, you get to wear fancy robes.
14. **Celebrate!*

----

# You and Your Major Professor {#you-and-your-major-professor}

In this section, I've provided some information regarding the process of choosing a major professor. If you're considering working with me, please be sure to read the section above on **Expectations**. Ideally, you and your Major Professor should be on the same page about what the expected work flow will be. Should we decide that working together is in your and your project's best interest, we will put together a Mentor-Mentee compact document that outlines the structure of our partnership. The Graduate School [provides examples of these compacts](https://grad.uga.edu/wp-content/uploads/2018/01/UAB-Mentor-Compact-adpated.pdf).


## Selecting a Chair and Committee {-}


----
<center>

Lunenburg, F. and D. Irby. (2008). [Writing a Successful Thesis or Dissertation: Tips and Strategies for Students in the Social and Behavioral Sciences](https://www.amazon.com/Writing-Successful-Thesis-Dissertation-Strategies/dp/141294225X). Thousand Oaks, CA: SAGE.</center>


----

Selecting your committee is a very important step in the process of preparing your dissertation or master's thesis. The chairperson of the committee usually has broad power and influence throughout the process of completing the dissertation or master's thesis.Therefore, the selection of a chairperson for your project is a very important decision. In collaboration with your chair and committee, you will delimit your topic, develop your proposal, conduct your research, and write your dissertation or master's thesis. Ultimately, your committee will judge the quality of your project. In this chapter, we present some suggestions that might help you in selecting your dissertation or thesis chair and other committee members.

Before choosing a faculty member as your chairperson, consider the chair's role. As mentioned previously, your chair will have broad  power and influence over the dissertation or thesis process. While the specifics of this role vary from institution to institution, from department to department, and from chairperson to chairperson, some general functions of the chair are relatively universal.  First, the chairperson will approve your dissertation or thesis topic.Second, the chairperson will approve, in consultation with you, the other committee members. Third, the chairperson will approve every line, section, and chapter of the dissertation.  Fourth, the chairperson will determine how committee members will be involved in the dissertation or thesis process.Fifth, the chairperson will decide when you are ready to defend your dissertation or master's thesis. And, ultimately, the chairperson will determine whether you will be granted the degree.

Most departments have rules concerning who may and who may not serve as dissertation or thesis chairpersons. Some universities allow only those individuals who are on the graduate faculty to serve as dissertation chairs; that is, faculty who have adequate, recent publication records and who teach graduate classes. These rules are based on the rationale that faculty who do not have active programs of research will lack the necessary skills to guide a doctoral research project.Rules regarding who may chair master's theses may not be as stringent as those concerning doctoral dissertations. Because practice varies on who may and who may not serve as dissertation chairs, we recommend that you learn your institution's rules as soon as possible.Knowing your institution's local ground rules will help you avoid considering a potential chairperson who is not eligible to chair a dissertation or thesis.

Selecting your committee is a very important step in the process of preparing your dissertation or master's thesis.  The chairperson of the committee usually has broad power and influence throughout the process of completing the dissertation or master's thesis.  Therefore, the selection of a chairperson for your project is a very important decision.  In collaboration with your chair and committee, you will delimit your topic, develop your proposal, conduct your research, and write your dissertation or master's thesis.  Ultimately, your committee will judge the quality of your project.  In this chapter, we present some suggestions that might help you in selecting your dissertation or thesis chair and other committee members.

Before choosing a faculty member as your chairperson, consider the chair's role.  As mentioned previously, your chair will have broad  power and influence over the dissertation or thesis process.  While the specifics of this role vary from institution to institution, from department to department, and from chairperson to chairperson, some general functions of the chair are relatively universal.  First, the chairperson will approve your dissertation or thesis topic.  Second, the chairperson will approve, in consultation with you, the other committee members.  Third, the chairperson will approve every line, section, and chapter of the dissertation.  Fourth, the chairperson will determine how committee members will be involved in the dissertation or thesis process.  Fifth, the chairperson will decide when you are ready to defend your dissertation or master's thesis.  And, ultimately, the chairperson will determine whether you will be granted the degree.

Most departments have rules concerning who may and who may not serve as dissertation or thesis chairpersons.  Some universities allow only those individuals who are on the graduate faculty to serve as dissertation chairs; that is, faculty who have adequate, recent publication records and who teach graduate classes. These rules are based on the rationale that faculty who do not have active programs of research will lack the necessary skills to guide a doctoral research project.  Rules regarding who may chair master's theses may not be as stringent as those concerning doctoral dissertations.  Because practice varies on who may and who may not serve as dissertation chairs, we recommend that you learn your institution's rules as soon as possible.  Knowing your institution's local ground rules will help you avoid considering a potential chairperson who is not eligible to chair a dissertation or thesis.

### Criteria to Consider in Selecting a Chair {-}

You must consider the following factors in choosing a chair: (a) expertise, (b) accessibility, (c) feedback, (d) success, (e) personality style, and (f) attitudes toward methodology.  The importance of each one will be discussed in turn.

### Expertise {-}

Ideally, it is in your best interest to find a chair with expertise in your topic area.  You may want to read some of your potential chair's publications.  In our opinion, following this advice generally will produce a better product.  Obviously, the closer your chair's area of expertise is to your topic, the more competent he or she will be to (a) identify difficulties you may encounter as you proceed with your study, (b) direct you toward literature sources pertinent to your topic, and (c) guide your choice of methods for collecting and anlayzing data.  Furthermore, a chair who has an interest and competence in your topic area is likely to be more invested in your project; that is, think through the project more fully and keep a vigilant eye on your progress than one who is not knowledgeable about your topic area, and, therefore, may lack interest in it as well.

### Accessibility {-}

Another important factor to consider in selecting a chair is accessibility.  Several things can interfere with a chair being consistently accessible to you during the life of your project.  When considering someone as a possible chair, you should think about these things.  Nationally known scholars may be too busy with their own research activity to give you the time you need.  Other faculty may have active clinical practices or be away from campus frequently due to consulting commitments.  Faculty members who have nine-month contracts with the university may not be available during the summer.  Faculty who are planning a sabbatical leave may potentially interrupt your progress.  Another faculty member may be planning to take a position in another university and, therefore, may not be available during the progress of your project.   One of the authors of this book had her chair go on sabbatical leave during the final semester of her dissertation work; therefore, a new chair had to be appointed.  Popular chairs may have an excessive number of dissertations or theses to monitor, because they are in high demand.

Then there is the issue of tenure.  Whereas nontenured faculty contracts may not be renewed, tenured faculty members are likely to be more stable.  You will need to consider the relative accessibility and stability of potential chairs, along with your own time constraints and projections for completion.

### Feedback {-}

Typically, the chair provides the first line of quality control for the dissertation or thesis.  And usually the chair will approve the proposal and final version of the project before you will be permitted to forward chapters of the dissertation or thesis to other committee members.  Therefore, look for a chair with a reputation for reading, critiquing, and returning written drafts promptly.

What is a good turnaround time?  A good rule of thumb is to allow two weeks for a response.  After that, a tactful inquiry may be appropriate.  Obviously, students should recognize that it might take longer during very busy periods (e.g., end of grading periods, holidays, and before graduation deadlines when all students want to finish their projects).

You should balance timelines of response with the thoroughness with which the potential chairperson reads submitted material. Some chairs provide vague feedback (e.g., rewrite this section), while others may provide detailed comments (e.g., "You need to identify the three main factors and then evaluate them in light of the theories you have discussed.").  Waiting longer for a chapter to be returned by a chair may have some positive consequences.  First, if you satisfy a chair who provides a thorough critique of your work, you are less likely to encounter serious problems with other committee members.  Second, you will be better prepared for your proposal defense and final oral defense of your dissertation or thesis.  Third, once you have satisfied your chair's standards, he or she is more likely to support you if one of your other committee members becomes overly or unreasonably critical of your work.

### Success {-}

Success at bringing students to graduation is an important factor to consider when selecting a chair.  Because you are concerned with completing your degree, count how many successful students your potential chair has; that is, what percentage of the chair's students finish their degrees.  Consider that criterion cautiously because some faculty members may not have had the opportunity to chair doctoral dissertations or master's theses.

### Personality Styles {-}
Personality styles matter to some people.  Writing a dissertation or thesis is a collaborative process between you and your chairperson.  Obviously, you want a chair with whom you can work reasonably well.  You will need to assess the match between what you expect from your chair and your chair's notion of the best way to perform his or her role.

Chairpersons vary greatly in how they work with students on dissertations and theses.  Those at one end of the continuum closely monitor each phase of the students' work, in some cases stipulating exactly what is to be done at every step, and then require the student to submit each section of material for critique. Chairs at the other end of the continuum tell students to progress on their own and to finish a complete draft of the project before submitting it for evaluation.  Most chairs will probably fall somewhere between these two extremes. Chairpersons also differ in the way they provide criticism.  Some are blunt and even derisive.  Others are direct and kindly in critiquing students' work.  Still others are so cautious of students' feeling when pointing out weaknesses that they fail to guide their students in correcting deficiencies.  In the latter case, someone else on the committee will have to step up and perform that duty; for the role of the chair and committee is to ensure that the candidate has met the university, college, and department standards.

Students also have personal preferences with whom they want to work, in general. For example, some students prefer to work with female faculty members, while others prefer to work with male faculty.  Some students prefer to work with older people, while others prefer younger faculty.

### Attitudes Toward Methodology {-}

Faculty members often differ concerning their preferences for a particular research method.  A research method comprises the strategy followed in collecting and analysing data.  The major distinction in classifying research by method is the distinction between quantitative and qualitative research 
[@gay_educational_2006].  Quantitative and qualitative research can be broken down further into several distinct types, each designed to answer a different kind of research question.  Quantitative research involves the collection and analysis of numerical data, which are usually rendered in the form of statistics.  Advocates of quantitative studies tend to prefer such types as descriptive (or survey), correlational, causal-comparative, and experimental research.  Proponents of such studies claim that their work is done from within a value-free framework [@denzin_sage_2005].

Qualitative research involves mostly nonnumerical data, such as extensive notes taken at a research site, interview data, videotape and audiotape recordings, and other nonnumerical artifacts.  Qualitative researchers stress the socially constructed nature of reality, the intimate relationship between the researcher and the participant, and the situational constraints that shape inquiry.  Qualitative researchers emphasize the value-laden nature of inquiry [@denzin_sage_2005]. Proponents of qualitative studies tend to favor such research approaches as case study, ethnography, ethology, ethnomethodology, grounded theory, phenomenology, symbolic interaction, and historical research.

You need to examine the match between your preference and your potential chair's preference for a research method. Many faculty members accept both quantitative and qualitative research methods, including the authors of this text.  We believe that the issue is not which method is better, but rather which method (quantitative, qualitative, or mixed methods) will best answer the particular research question or direction of inquiry.


## Questions to consider in selecting an advisor {-}

These questions have been adapted from a document prepared by the Graduate School at the University of Pittsburgh.

1. Is the advisor an expert in the area of research or scholarship that you intend to pursue? Is his/her critical or theoretical orientation consistent with yours?
2. How much freedom will you have in your choice of dissertation topic with this advisor?
3. What is the reputation of the advisor within the discipline?
4. How responsive is the advisor? How long does it take him/her to return written material with comments?
5. How accessible is the advisor for discussion?
6. Is the advisor likely to remain on the faculty for the duration of your degree work?
7. How many students does he/she advise? If none, why? If a large number, does this affect the attention that he/she pays to individual students?
8. How much time does he/she spend away from campus? Is he/she available during the summer?
9. How long do students take to complete their degrees with this advisor?
10. What proportion of this advisor's students successfully complete the program?
11. What is the placement record of this advisor's students? Where do they get jobs?
12. Does the advisor publish with his/her students as first author?
13. How many publications does the typical student accumulate with this advisor?
14. Do the advisor's students go to disciplinary or professional conferences?
15. Do the advisor's students make presentations of their own work at conferences? Do they make presentations of joint work with the advisor?
16. How much interaction is there with other advisees of this faculty member? Does he/she direct a research group or rather a series of individuals?
17. How much of the research is collaborative with the advisor and/or other advisees?
18. How much involvement is expected in ``group'' research projects that are not appropriate for inclusion in your dissertation? How much of this contributes to your professional development and marketability?
19. How is credit for collaborative work assigned?
20. Is the advisor's work funded? What are the guarantees of funding for the advisor's students? Do the advisor's students get summer support?
21. Does the advisor assist his/her students in obtaining their own funding from outside sources such as fellowship programs?
22. Does the advisor have good relations with other faculty in the program?
23. Does the advisor have a reputation for ethical behavior?
24. Are the advisor's work habits compatible with your own?

> **_Note_** Not all of these questions are equally important when choosing a Major Professor to direct an MA thesis. You should, however, consider these issues when choosing someone to work with, whether it be at the MA or the PhD level. Also, don;t be afraid to ask your professors for ideas about topics. At the MA level, you aren't necessarily expected to come armed with a full-fledged research topic in hand.


----


## Guidelines for Good Practice in Graduate Education {-}

The expectations for each graduate student are to develop an understanding of and capacity for scholarship, independent judgment, academic rigor, and intellectual honesty. As such, graduate faculty are responsible for fostering and facilitating the student's professional development to meet these expectations.^[Guidelines are for instructive purposes and do not constitute statements of institutional policy or requirements. Approved by the University of Georgia Graduate Council on April 18, 2007.]

Guiding principles for which both graduate faculty and students share responsibility:

1. Ensure that the relationship between faculty and students and among students is constructive, encourages freedom of inquiry, and fosters mutual respect.
2. Work respectfully with diverse faculty, students and peers regardless of race, gender, religion, sexual orientation, or national origin.
3. Act with professionalism, ethical conduct, and personal accountability during all academic endeavors and interactions among students and faculty.
3. Make explicit the expectations of graduate students and faculty for relevant elements of graduate student activities; assess progress in meeting these expectations and provide/use constructive feedback.
4. Put forth sufficient effort to ensure the graduate student completes the degree and assistantship responsibilities in timely manner.
5. Agree that students are expected to take initiative in learning and carrying out other responsibilities (versus expecting faculty to provide everything). Faculty are expected to facilitate learning and professional development (versus expecting students to be able to carry out all responsibilities, e.g., teaching with no guidance).
6. Have reasonable expectations for the time available for graduate student-related tasks. Faculty and students have many responsibilities. Thus, both parties need to respect the others' need for sufficient time to complete all responsibilities.
7. Avoid conflicts of interest of any nature between faculty and graduate students.



----


# A Guide to Your Research

> **_Note_** This section is still very much under construction [insert animated icon of worker here].

Much of the following information is summarized from [How to Be a Successful PhD Student](http://people.cs.umass.edu/~wallach/how_to_be_a_successful_phd_student.pdf) (by Mark Dredze at Johns Hopkins University and Hanna M. Wallach University of Massachusetts Amherst). The this document is directed primarily at doctoral students, though much of the advice applies equally well for MA students.

## Managing your time

Transitioning into a graduate program (especially if you're teaching) involves a good deal of time management. It's often difficult (at least it was for me) to start thinking of your chosen discipline (e.g., Spanish, linguistics) as a job rather than as a hobby. It will help if you start treating your time as you would if you had a `normal', 9-to-5 job.

1. You are in graduate school, and **research** should be your main focus. Developing good habits in your teaching is certainly important at this stage. But your the lion's share of your attention should be paid to your research agenda. As Dredze and Wallach note, ``[d]o well enough in your [teaching] but focus on publishing high quality research papers.''
2. **Interacting** with other students in your program (and from other programs) is crucial. Research should not be done (at least not exclusively) by yourself alone in a room with books. Create mechanism for getting feedback from your colleagues.
3. Keeping a **regular work schedule** in graduate school is crucial. This is especially true as you move into the thesis or dissertation writing phase.
4. You should **keep a work log**. This should include (a) projects that you're developing, (b) ideas you have about those projects, (c) records for data gathering/analysis. As a linguist, having a notebook to jot down the quirky and interesting things that people say will become second nature. Many famous papers started out as doodles and scribbled notes.

## Research

1. **Read!** Much of the time you spend doing `research' should be spent (1) reading articles, books, chapters, etc. related to your work and (2) (re-)reading your own work. Keeping up with the current trends in the discipline means investing considerable time in reading other people's (and your own) research.
2. Coming up with a topic is perhaps one of the most difficult parts of the research process. [Dredze and Wallach](http://people.cs.umass.edu/~wallach/how_to_be_a_successful_phd_student.pdf) provide a nice overview of how to approach this issue. Keep in mind that if you plan to have a career in academia, there will be plenty of time for you to work on different topics down the road (thus the need for a notebook to write down those ideas).


----

# Funding resources

If you plan to work with me, chances are that you will be encouraged/required (1) to conduct fieldwork as part of your thesis/dissertation project and (2) attend conferences. All these endeavors cost money, but fortunately there are some funds available for you (as well as access to the types of equipment you'll need to actually conduct your work). Here are a few possible sources that you should consider when planning your research projects. When applying for grants, I like to encourage the Wayne Gretzky principle: "You miss 100 percent of the shots you never take."

1. **Funded projects**: In some cases, your professors will have projects that have been funded by internal or external grant agencies. Sometimes, funds are ear-marked for paying graduate students to do tasks related to the project (e.g., transcribing data, travel, etc.). You should inquire with your professors about these types of opportunities. For the most part, if a particular professor has a project with funding for graduate student participation, s/he will come looking for a possible RA.
2. [Tinker Graduate Research Award](https://lacsi.uga.edu/funding-available-tinker-graduate-research-award): These grants are administered through the [Latin American and Caribbean Studies Institute](https://lacsi.uga.edu/) (though they aren't always referred to as Tinker Grants) and are designed to fund research for the completion of MA thesis or doctoral dissertations. The deadline for submitting applications is usually early to mid Spring. If you would like a sample application or comments on your application, just ask me or one of your other professors; we are always glad to help.
3. [Willson Center Graduate Research Award](https://willson.uga.edu/opportunities/fellowships-grants/willson-grants-awards/): The Willson Center offers opportunities for Graduate Students, in particular the **Graduate Research Award**, with deadlines in September and January. This award provides support of up to \$1,250 (subject to change) to arts and humanities graduate students for relevant expenses related to completion of their degrees. Graduate students may be supported in travel to archives, installations and performances. Reason must be given for support of the proposed activity in context of research excellence. There are two deadlines during the year: <font size="3" color="red">August 29</font> and <font size="3" color="red">January</font>. The Willson Center also provides funds for travel to conferences and professional meetings. 
4. **Funds for Graduate Student Travel**: Though the funds are limited (and the competition fierce), you should consider applying for travel funds through the [Graduate School](https://grad.uga.edu/). The funds are usually just for Doctoral students, but it never hurts to ask. There are also funds available through the the Department of Romance Languages and the Department of Linguistics.
5.  **Dissertation Completion Award** This is a highly competitive award for doctoral students who have passed to candidacy (i.e. ABD). This awards typically requires nomination and selection at the Departmental level. The applications are typically due in the spring, but if you're interested you should inquire early.
6. [The Dolores Artau Scholarship](https://rom.uga.edu/dolores-artau-scholarship): The Department of Romance Languages has a limited number of funding opportunities available to grad students (e.g., the Dolores Artau Scholarship).
7. [Pivot COS](https://pivot.proquest.com/) is a subscription database of more than 25,000 funding opportunities from numerous sponsors across all disciplines. UGA faculty, students, and staff can search the database and create custom email funding alerts based on the criteria provided by the individual COS user. You can also share funding opportunities with groups, and save and track opportunities. It's a \textbf{very} useful tool. I would recommend that you start using it immediately. The library offers [a nice tutorial on how to use this resource](https://guides.libs.uga.edu/grants/pivot).
8. **Fulbright Grants for student research abroad**: This is a great source of funds. The deadline is usually sometime in the early fall.
9. **Summer Research Travel Grants for Graduate Students**: Grant money ($2000) offered by the UGA Graduate School. Funds are intended to support research-related travel. Proposals due in **late February**.
10. **Summer Doctoral Research Assistantship**: "The purpose of this assistantship is to provide summer funding of doctoral candidates in the fine arts, humanities, and selected social science and professional programs administered by the Graduate School, so the students may focus exclusively on their dissertation research and writing." Proposals due in **February**.
11. **UGA Graduate School Dean's Award**: Established to assist graduate students in defraying the cost of performing research for their dissertation or thesis and to help them complete their degree." Proposals due in **March**.
12. **UGA Innovative and Interdisciplinary Research Grant for Graduate Students**: Funds provided by the UGA Graduate School to support research. Propsoals due in **February**.
13. [NSF Doctoral Dissertation Research Improvement Grants](https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=505033&org=NSF) (LING-DDRI): These are *highly* competitive grants for work related to dissertation projects. Proposals are due <font size="3" color="red">July 15th and January 15th</font>.
14. [The *Langauge Learning* Dissertation Grant Program](https://onlinelibrary.wiley.com/page/journal/14679922/homepage/grant_programs.htm): This program "supports the dissertation research of doctoral candidates in the language sciences."
15. [International Dissertation Rsearch Fellowship (IDRF)](https://www.ssrc.org/fellowships/view/idrf-fellowship/): This program is open to graduate students in "the humanities and humanistic social sciences". The deadline is in the fall.

There are of course other sources of funding that you can take advantage of. If you happen to run across any others that look particularly appealing, let me know. In all of these cases, I will be happy to provide you with letters of support.


----

# Prospectus Outline

The following are guidelines for preparing your thesis or dissertation prospectus (prepared by Dr. Margaret Lubbers Quesada). Your prospectus should be approximately 10 pages (for MA thesis) or 20+ pages (for dissertation).

1. **Statement of Problem** (1/2-1 page): What is the problem to be studied and why is it of interest?  Illustrate with examples and mention 2-3 sources/studies that have been carried out covering this topic.
2.	**Review of the literature** (4-6 pages) In this section, you will briefly describe the studies that have been carried out on this topic and upon which your own research is based.  For each study, include what the purpose was, what the methodology was (who the participants were, what the instruments were, how the data were analyzed), and what the results were.  Use this section to justify your research and specifically, point out how these studies are related to yours and what your study will do to answer questions about the topic that these studies do not answer.  For the prospectus, 6-8 studies should be reviewed.  For the thesis, you will expand this section to 10-12 studies. At the end of this section, it should clear to your readers what the open questions in the literature are.
3.	**Research questions and/or hypotheses** (1/2-1 page): You should have 2-3 questions that will guide your research.  If there has been enough research done on the topic or if you are choosing an experimental or quasi-experimental design, you can postulate hypotheses, which should result from the questions.  For example, a research question might be:  *Do Spanish/English bilinguals have higher rates of overt subject expression in Spanish than monolinguals?*  And the hypothesis set up to answer the question would be:  *Spanish/English bilinguals have higher rates of overt subject expression due to contact with English*.  The hypotheses have to be worded so that they are testable and falsifiable.  Also, define any terms that have not been defined in the literature review.
4.	**Methodology** (2-3 pages):  Include in this section, the following:
      + **Participants** (age, language level or knowledge, gender, social or economic level if related to research questions).
      + **Context** (i.e. where the data will be gathered)
      + **Instruments** (if you have already worked out the data collection instrument(s), attach this as an appendix)
      +  Procedure for **collecting** data
      + Procedures for **analysis** including any statistical analyses that may be applied
5. **Expected results and conclusions** (1/2-1 page): Discuss to what extent you expect to answer your research questions and/or prove or disprove your hypotheses.
6. **References**: For linguistics and applied linguistics thesis, the [LSA format is preferred](http://www.linguisticsociety.org/files/style-sheet.pdf) but you can also use the APA or MLA formats. 


----

Last updated on **`r params$d`**.

----

