---
title: "Resources"
output: 
  html_document:
    toc: true
    toc_float: true
---

Below is a list a resources that students might find useful for their research (and teaching). I've pillaged heavily (and, in some instances, copied) [Dr. Peggy Renwick's thorough list of resources](http://faculty.franklin.uga.edu/mrenwick/phonetics-phonology-resources). Suggestions welcome!

## Tools for data analysis
- [UGA Statistical Consulting Center](http://www.stat.uga.edu/consulting)
- [The R Project](http://www.r-project.org/)
- [RStudio](https://www.rstudio.com/): If you use R, you should use RStudio
- [Rbrul](http://www.danielezrajohnson.com/rbrul.html): An R implementation of GoldVarb-style regression analysis by Daniel Ezra Johnson
- [Language Variation Suite](https://languagevariationsuite.shinyapps.io/Pages/): tools for quantitative data analysis
- [ELAN](https://tla.mpi.nl/tools/tla-tools/elan/): a very useful tool for transcribing and annotating linguistic data
- [Transcriber](http://trans.sourceforge.net/en/presentation.php): a tool for segmenting, labeling and transcribing speech
- [SPPAS](http://www.sppas.org/): "The automatic annotation and analyses of speech, is a scientific computer software tool, daily developed with the aim to be a robust and reliable software."
- [Praat](http://www.fon.hum.uva.nl/praat/): The (linguistics) industry standard in doing phonetic analysis
- [Soundtrap](https://www.soundtrap.com/): This is a nifty online platform for conducting and recording interviews. In addition to a wide range of users (e.g., podcasters, radio programs, etc.), it allows for different linguist-friendly functions, such as good-quality audio and (some) automatic transcriptions (in English).
- [Data Collection in Sociolinguistics: Methods and Applications](https://sociolinguisticdatacollection.com/): This is a very nice volume edited by Christine Mallison, Becky Childs, and Gerard Van Herk. The website has lots of useful resources.
- [Method Bites](https://www.mzes.uni-mannheim.de/socialsciencedatalab/): Blog of the MZES Social Science Data Lab (lots of great tutorials)
- [Data Visualization: A practical introduction](https://socviz.co/): A great source for using R to make graphs n' such.

## Corpora and Corpus tools
- [Collection of corpus resources available to UGA faculty and students](http://research.franklin.uga.edu/linglab/corpora)
- [Corpus del Español](http://www.corpusdelespanol.org/): Spanish corpus run out of BYU
- <a href="http://www.corpusdoportugues.org/">Corpus do Português</a>; Portuguese corpus run out BYU
- <a href="http://preseea.linguas.net/">PRESEEA</a>: A collection of sociolinguistic data from around the Spanish-speaking world
- <a href="http://www.rae.es/recursos/banco-de-datos">Real Academia Española</a>: different synchronic and diachronic corpora
- <a href="https://www.webcorpora.org/">COW</a>: High Quality Web Corpora
- <a href="http://corpora.lancs.ac.uk/lancsbox/">LANCSBox</a>: software package for the analysis of language data and corpora
- [Lancaster Stats Tools online](http://corpora.lancs.ac.uk/stats/index.php): The website provides practical support for the analysis of corpus data using a range of statistical techniques.
- <a href="https://uclouvain.be/en/research-institutes/ilc/cecl/corpora.html">Center for English Corpus Linguistics (Louvain)</a>: A collection of several useful corpus resources
- <a href="http://lingtools.uoregon.edu/coraal/explorer/">CoRAAL</a>: Corpus of Regional African American Language, developed and hosted by the University Oregon
- <a href="https://cqpweb.lancs.ac.uk/">Lancaster Corpus Resources</a>
- <a href="https://cesa.arizona.edu/links-other-sociolinguistic-corpora">University of Arizona Corpus Resources</a>
- [SPeech Across Dialects of English (SPADE)](https://spade.glasgow.ac.uk/): This is a very cool project that seeks to develop tools for doing large-scale analysis of speech data.
- [Linguistic Data Consortium](https://www.ldc.upenn.edu/): A great resource for language corpora; and UGA has an institutional subscription!!
- [Tools for Corpus Linguistics](https://corpus-analysis.com/): A long list of corpus-related resources that's always being updated


## Other Tools and Resources
- <a href="http://www.essex.ac.uk/linguistics/external/clmt/latex4ling/">LaTeX for Linguists</a>
- <a href="https://rmarkdown.rstudio.com/">RMarkdown</a>: A markup language useful for creating documents and presentations (and other delights)
- <a href="https://www.linguisticsociety.org/sites/default/files/style-sheet.pdf"><em>Language</em> style sheet</a>
- <a href="http://www.overleaf.com">Overleaf</a>: A nifty resource for creating LaTeX documents online. Also has some very handy collaboration functions.
- [Bib Converter](http://glottotopia.org/doc2tex/doc2bib): This is a **very** nifty tool to convert a Unified Style Sheet bibliography to bibtex.


## Resources for Graduate Students
- [UGA Grad School Professional Development](https://grad.uga.edu/index.php/current-students/professional-development/): Services, resources, and opportunities available through the UGA Grad School
- <a href="https://tomprof.stanford.edu/posting/1482">"Choosing a Dissertation Topic"</a>&nbsp;(Post from&nbsp;<em>Tomorrow's Professor)</em>
- <a href="http://www.nature.com/nchembio/journal/v6/n2/full/nchembio.310.html">"On citing well", in <em>Nature Chemical Biology</em></a>
- <a href="http://www.phdcomics.com/comics.php">PhD Comics</a>
- <a href="http://www.cascadilla.com/surviving.html"><em>Surviving Linguistics: A Guide for Graduate Students</em> (Monica Macaulay)</a>
- <a href="http://www.amazon.com/Writing-Your-Dissertation-Fifteen-Minutes/dp/080504891X"><em>Writing your dissertation in 15 minutes a day</em> (Joan Bolker)</a>
- ["How to edit your own writing", NYT article by Harry Guinness](https://www.nytimes.com/2020/04/07/smarter-living/how-to-edit-your-own-writing.html?algo=identity&fellback=false&imp_id=366739603&imp_id=908833036&action=click&module=Smarter%20Living&pgtype=Homepage)
- [The Professor is In](http://theprofessorisin.com/): Blog, book, and other materials by Dr. Karen L. Kelsky
- [*Handbook for Academic Authors* by Beth Luey](http://www.bethluey.com/handbook_for_academic_authors_47173.htm) [[Amazon](https://www.amazon.com/Handbook-Academic-Authors-Beth-Luey/dp/0521144094)]
- [*Stylish Academic Writing* by Helen Sword](https://www.helensword.com/)  [[Amazon](https://www.amazon.com/Stylish-Academic-Writing-Helen-Sword/dp/0674064488)]
- [The MLA's Line by Line: How to Edit Your Own Writing](https://www.amazon.com/MLAs-Line-Writing-Language-Association/dp/B004XTN9HU)
- [*The Sense of Style: the Thinking Person's Guide to Writing in the 21st Century* by Steven Pinker](http://xidian-usa.org/wp-content/uploads/2019/07/The-Sense-of-Style.pdf)

## Runasimimanta
- <a href="https://web.sas.upenn.edu/quechua/">Quechua at Penn</a>: Quechua and Andean Culture (University of Pennsylvania)
- <a href="https://as.nyu.edu/content/nyu-as/as/research-centers/clacs/quechua.html">Quechua @ NYU</a>: Information about Quechua offerings at NYU
- <a href="https://kichwahatari.org/">Kichwa Hatari</a>: a weekly radio program, the first in the indigenous Kichwa language in the U.S, aimed at reaching the Quechua/Kichwa population in the United States, particularly in New York
- <a href="http://amlq.org.pe/">Academia Mayor de la Lengua Quechua</a>: Information about Quechua language and culture
- <a href="http://www.clacs.illinois.edu/quechua/">Quechua at UIUC</a>: Information about the Quechua offerings at the University of Illinois Urbana-Champaign
- <a href="http://www.quechua.org.uk/">Quechua</a>: A somewhat dated but <strong>very </strong>useful collection of resources for folks interested in Quechua/Quichua/Runasimi
- [Linguistics Summer School Bolivia](https://www.lssbolivia.com/?fbclid=IwAR0RdJpESc70ZuTjig1HtGsB2k9cRdb5lAzF3wzkuBe0nDFbATUjN7oYdCY): This institution offers training to speakers of indigenous languages and applied linguistics students.

## Digital Humanities
I'm not particularly qualified to provide a list of useful resources for this topic, but that hasn't stopped me thus far. Again, I'm taking heavily from resources that have been suggested to me by students and colleagues (specifically [Dr. Nora Benedict](https://norabenedict.github.io/index.html))

- [UGA DigiLab](https://digi.uga.edu/digilab/#1544564021635-6ae22572-cb2d): In addition to being a cool physical space, the DigiLab, directed by Dr. Emily McGinn, offers **lots** of resources and events for faculty and students.
- [Digital Pedagogy in the Humanities](https://digitalpedagogy.hcommons.org/?utm_campaign=digestapr20non&utm_medium=email&utm_source=mlaoutreach): This is a useful collection of materials and tools curated by the MLA.
- [*Debates in the Digital Humanities*](https://dhdebates.gc.cuny.edu/): This a nice resource for up-to-date research.
- [RAWGraphs](https://rawgraphs.io/): I've not used this one, but Dr. Benedict endorses it.
- [Palladio](https://hdlab.stanford.edu/palladio/): This is a handy visualization tool. It's particularly useful for historical data.
- [OpenRefine](https://openrefine.org/): Very useful for managing messy data. Not terribly different (in spirit) from TidyVerse.
- [Voyant Tools](https://voyant-tools.org/): Useful for basic text analysis.
- [Dr. Miriam Posner's Blog](https://miriamposner.com/blog/tutorials-ive-written/): There are a number of **really** nice tutorials on Dr. Posner's website.
- [Digital Humanities Journals](https://digitalhumanities.berkeley.edu/resources/digital-humanities-journals): This is a list maintained by the DH folks at Berkeley. In addition to the other DH resources, it's a good reference.


## Stay connected / Get involved
There are lots of ways to stay active in the linguistics community at UGA. In Romance Languages, there are [weekly conversation groups](http://rom.uga.edu/conversation-groups-and-language-tables) for French, Italian, Portuguese, and Spanish (and sometimes Catalan), as well as the [Romance Languages Colloquium](http://rom.uga.edu/events/all). In the [Department of Linguistics](http://www.linguistics.uga.edu/department-calendar), there are regular talks by internal and external speakers and several events hosted by the [Linguistics Society at the University of Georgia (LSUGA)](http://www.linguistics.uga.edu/lsuga), including the [Linguistics Conference at UGA](http://www.linguistics.uga.edu/linguistics-conference), now in its sixth iteration. Finally, if you're interested in joining one of our listservs, please contact me for access to either the **Romance Linguistics Listserv (ROMLING-L)** or the **Latin American Indigenous Languages Listserv (LAIL-L)**. 

- [The Center for Latino Achievement and Success in Education](https://coe.uga.edu/directory/latino-achievement): **CLASE** is an "educational research and development center" housed in the Mary Frances Early College of Education at UGA. They have tons of cool initiatives and projects. Also, our very own [Shannon Rodríguez](https://www.linguistics.uga.edu/directory/people/shannon-rodriguez) is a Graduate Research Assistant with CLASE.
- <a href="http://languagelog.ldc.upenn.edu/nll/">Language Log</a>: A great (and in fact award-winning)&nbsp;blog for linguists
- <a href="https://lingthusiasm.com/">Lingthusiasm</a>: podcast that's enthusiastic about linguistics by Gretchen McCulloch and Lauren Gawne.
- <a href="http://www.languageonthemove.com/#">Language on the Move</a>: a peer-reviewed sociolinguistics research site devoted to multilingualism, language learning and intercultural communication in the contexts of globalization and migration
- <a href="https://citizensociolinguistics.com/">Citizen Sociolinguistics</a>: A great blog by Prof. Betsy Rymes at the University of Pennsylvania
- <a href="http://www.athensoconeecasa.org/">Athens-Oconee CASA</a>: Court Appointed Special Advocates
- [Casa de Amistad](http://athensamistad.com/): Casa de Amistad works with the Latino and Hispanic population in the Northeast Georgia area. They provide social services, referrals, translation, education and advocacy.
- <a href="https://athensforeveryone.com/">Athens for Everyone</a>

----


